# Numpy

## The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

### Use the following import convention:

In [1]:
import numpy as np

## Numpy Array
1D Array  axis = 0
2D Array axis = 0, axis = 1
3D Array axis = 0, axis = 1, axis = 2

## Creating Arrays

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
b1 = np.array([(2,3,4), (6,7,8)], dtype = float)
b1

array([[2., 3., 4.],
       [6., 7., 8.]])

In [4]:
b1 = np.array([[2,3,4], [6,7,8]], dtype = float)
b1

array([[2., 3., 4.],
       [6., 7., 8.]])

In [5]:
c1 = np.array([[3,34,45], [66,78,86], [23,54,68]])
c1

array([[ 3, 34, 45],
       [66, 78, 86],
       [23, 54, 68]])

# Create an array of zeros

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros([2,3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

###  Create an array of ones

In [10]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

### Create an array of evenly spaced values (step values)

In [13]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [14]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

### Create an array of evenly spaced values (number of samples)

In [15]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [17]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

### Create a constant array

In [18]:
c = np.full((2,2),7)
c

array([[7, 7],
       [7, 7]])

In [19]:
d = np.full((4,4), 8)
d

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

### Create a 2X2 identity matrix

In [20]:
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Create an array with random values

In [22]:
np.random.random((2,2))

array([[0.8061898 , 0.84633411],
       [0.48738241, 0.94209482]])

In [23]:
np.random.random((4,5))

array([[0.92035209, 0.58959836, 0.84789844, 0.8933382 , 0.54693751],
       [0.91729628, 0.61334978, 0.55184248, 0.8756318 , 0.82001243],
       [0.53268977, 0.29085022, 0.59455233, 0.44561157, 0.4963865 ],
       [0.34748339, 0.49531915, 0.15357996, 0.90156207, 0.54184512]])

### Create an empty array

In [24]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty((4,5))

array([[0.92035209, 0.58959836, 0.84789844, 0.8933382 , 0.54693751],
       [0.91729628, 0.61334978, 0.55184248, 0.8756318 , 0.82001243],
       [0.53268977, 0.29085022, 0.59455233, 0.44561157, 0.4963865 ],
       [0.34748339, 0.49531915, 0.15357996, 0.90156207, 0.54184512]])

# Input/Output

## Saving & Loading On Disk

In [26]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [27]:
np.save("my_array", a)

In [28]:
np.savez('my_name.npz', a,b)

In [29]:
np.savez('file_name', a, b)

In [30]:
# np.load('file_name.npy')

In [31]:
np.load('my_array.npy')

array([2, 4, 6, 8])

### Saving & Loading Text Files

In [32]:
# > np.loadtxt("myfile.txt")
# >>> np.genfromtxt("my_file.csv", delimiter=',')
# >>> np.savetxt("myarray.txt", a, delimiter=" ")

In [33]:
# np.loadtxt("myfile.txt")

In [34]:
np.savetxt("myarray.txt", a, delimiter = '')

In [35]:
# np.genfromtxt("filename.csv", delimiter = ',')

# Data Types

### Signed 64-bit integer types

In [36]:
np.int64

numpy.int64

In [37]:
np.int(64)

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\1249397564.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.int(64)


64

In [38]:
# np.int44

### Standard double-precision floating point

In [39]:
np.float32

numpy.float32

In [40]:
np.float(34.56)

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\1181887926.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(34.56)


34.56

In [41]:
# np.float34.5

### Complex numbers represented by 128 floats

In [42]:
np.complex

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\82300521.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex


complex

### Boolean type storing TRUE and FALSE values

In [43]:
np.bool

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\3526611434.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool


bool

### Python object type

In [44]:
np.object

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\1847956310.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object


object

### Fixed-length string type

In [45]:
np.string_

numpy.bytes_

In [46]:
# np.string

### Fixed-length unicode type

In [47]:
np.unicode

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\1267029257.py:1: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.unicode


str

In [48]:
np.unicode_

numpy.str_

# Inspecting Your Array

### Array dimensions

In [49]:
a1

array([1, 2, 3])

In [50]:
b1

array([[2., 3., 4.],
       [6., 7., 8.]])

In [51]:
a1.shape

(3,)

In [52]:
b1.shape

(2, 3)

### Length of array 

In [53]:
len(a1)

3

In [54]:
len(b1)

2

### Number of array dimensions 

In [55]:
np.ndim

<function numpy.ndim(a)>

In [56]:
d1 = np.array([(54,56,34,78), (23,65,78,4), (31,14,68,45), (12,56,34,34)])
d1

array([[54, 56, 34, 78],
       [23, 65, 78,  4],
       [31, 14, 68, 45],
       [12, 56, 34, 34]])

In [57]:
d1.ndim

2

In [58]:
a.ndim

1

In [59]:
a1.ndim

1

In [60]:
b1.ndim

2

In [61]:
c1.ndim

2

In [62]:
b.ndim

1

In [63]:
np.ndim(a1)

1

In [64]:
np.ndim(b1)

2

In [65]:
e = np.arange(2,10,2)
e

array([2, 4, 6, 8])

In [66]:
g = np.arange(6)
g

array([0, 1, 2, 3, 4, 5])

In [67]:
# np.arange(6).reshape(2,3)     # or
h = g.reshape(2,3)
h

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
i = np.arange(9).reshape((3,3))
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
j = np.arange(18).reshape(2,3,3)
j

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [70]:
a_2d = np.arange(12).reshape((3, 4))
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Number of array elements

In [71]:
i.size

9

In [72]:
j.size

18

In [73]:
e.size

4

### Data type of array elements

In [74]:
a.dtype

dtype('int32')

In [75]:
# dtypes(a)
# dtype(a)
# dtype.a

In [76]:
b.dtype

dtype('int32')

### Name of data type 

In [77]:
b.dtype.name

'int32'

In [78]:
i.dtype.name

'int32'

In [79]:
i.dtype

dtype('int32')

In [80]:
# b.dtype.Name

### Convert an array to a different type

In [81]:
b.astype(int)

array([1, 3, 5, 7, 9])

In [82]:
b.astype(float)

array([1., 3., 5., 7., 9.])

# Asking for help

In [83]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [84]:
np.info(j)

class:  ndarray
shape:  (2, 3, 3)
strides:  (36, 12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f723ef26b0
byteorder:  little
byteswap:  False
type: int32


# Array Mathematics

## Arithmetic Operations

### Addition

In [85]:
a11 = np.array([(2,3,4), (23,45,67), (43,65,87)])
a11

array([[ 2,  3,  4],
       [23, 45, 67],
       [43, 65, 87]])

In [86]:
b11 = np.array([(32,43,54), (13,23,15), (98,54,67)])
b11

array([[32, 43, 54],
       [13, 23, 15],
       [98, 54, 67]])

In [87]:
c11 = np.array([(90,12,67), (43,23,36), (16, 78,98)])
c11

array([[90, 12, 67],
       [43, 23, 36],
       [16, 78, 98]])

In [88]:
d11 = a11 + b11
d11

array([[ 34,  46,  58],
       [ 36,  68,  82],
       [141, 119, 154]])

In [89]:
d11 = np.add(a11, b11, c11)
d11

array([[ 34,  46,  58],
       [ 36,  68,  82],
       [141, 119, 154]])

### Subtraction

In [90]:
e11 = a11 - b11
e11

array([[-30, -40, -50],
       [ 10,  22,  52],
       [-55,  11,  20]])

In [91]:
f11 = np.subtract(a11,c11)
f11

array([[-32, -43, -54],
       [-13, -23, -15],
       [-98, -54, -67]])

In [92]:
g11 = np.subtract(a11, b11, c11)
g11

array([[-30, -40, -50],
       [ 10,  22,  52],
       [-55,  11,  20]])

### Multiplication

In [93]:
h11 = a11*b11
h11

array([[  64,  129,  216],
       [ 299, 1035, 1005],
       [4214, 3510, 5829]])

In [94]:
c11

array([[-30, -40, -50],
       [ 10,  22,  52],
       [-55,  11,  20]])

In [95]:
i11 = c11 * b11
i11

array([[ -960, -1720, -2700],
       [  130,   506,   780],
       [-5390,   594,  1340]])

### Division

In [96]:
j11 = np.divide(c11, a11)
j11

array([[-15.        , -13.33333333, -12.5       ],
       [  0.43478261,   0.48888889,   0.7761194 ],
       [ -1.27906977,   0.16923077,   0.22988506]])

In [97]:
k11 = c11/b11
k11

array([[-0.9375    , -0.93023256, -0.92592593],
       [ 0.76923077,  0.95652174,  3.46666667],
       [-0.56122449,  0.2037037 ,  0.29850746]])

### Exponentiation

In [98]:
np.exp(a11)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [9.74480345e+09, 3.49342711e+19, 1.25236317e+29],
       [4.72783947e+18, 1.69488924e+28, 6.07603023e+37]])

In [99]:
np.exp(b11)

array([[7.89629602e+13, 4.72783947e+18, 2.83075330e+23],
       [4.42413392e+05, 9.74480345e+09, 3.26901737e+06],
       [3.63797095e+42, 2.83075330e+23, 1.25236317e+29]])

In [100]:
np.exp(c11)

array([[9.35762297e-14, 4.24835426e-18, 1.92874985e-22],
       [2.20264658e+04, 3.58491285e+09, 3.83100800e+22],
       [1.29958143e-24, 5.98741417e+04, 4.85165195e+08]])

### Square Root

In [101]:
np.sqrt(a11)

array([[1.41421356, 1.73205081, 2.        ],
       [4.79583152, 6.70820393, 8.18535277],
       [6.55743852, 8.06225775, 9.32737905]])

In [102]:
np.sqrt(b11)

array([[5.65685425, 6.55743852, 7.34846923],
       [3.60555128, 4.79583152, 3.87298335],
       [9.89949494, 7.34846923, 8.18535277]])

In [103]:
np.sqrt(c11)

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\1042593601.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(c11)


array([[       nan,        nan,        nan],
       [3.16227766, 4.69041576, 7.21110255],
       [       nan, 3.31662479, 4.47213595]])

### Sin

In [104]:
np.sin(a11)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.8462204 ,  0.85090352, -0.85551998],
       [-0.83177474,  0.82682868, -0.82181784]])

In [105]:
np.sin(b11)

array([[ 0.55142668, -0.83177474, -0.55878905],
       [ 0.42016704, -0.8462204 ,  0.65028784],
       [-0.57338187, -0.55878905, -0.85551998]])

In [106]:
np.sin(c11)

array([[ 0.98803162, -0.74511316,  0.26237485],
       [-0.54402111, -0.00885131,  0.98662759],
       [ 0.99975517, -0.99999021,  0.91294525]])

### Cos

In [107]:
np.cos(a11)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [-0.53283302,  0.52532199, -0.5177698 ],
       [ 0.5551133 , -0.56245385,  0.56975033]])

In [108]:
np.cos(b11)

array([[ 0.83422336,  0.5551133 , -0.82930983],
       [ 0.90744678, -0.53283302, -0.75968791],
       [-0.81928825, -0.82930983, -0.5177698 ]])

In [109]:
np.cos(c11)

array([[ 0.15425145, -0.66693806,  0.96496603],
       [-0.83907153, -0.99996083, -0.16299078],
       [ 0.02212676,  0.0044257 ,  0.40808206]])

### Tangent

In [110]:
np.tan(a11)

array([[-2.18503986, -0.14254654,  1.15782128],
       [ 1.58815308,  1.61977519,  1.65231726],
       [-1.49838734, -1.47003826, -1.44241747]])

In [111]:
np.tan(b11)

array([[ 0.66100604, -1.49838734,  0.6738001 ],
       [ 0.46302113,  1.58815308, -0.8559934 ],
       [ 0.69985365,  0.6738001 ,  1.65231726]])

In [112]:
np.tan(c11)

array([[ 6.40533120e+00,  1.11721493e+00,  2.71900612e-01],
       [ 6.48360827e-01,  8.85165604e-03, -6.05327238e+00],
       [ 4.51830879e+01, -2.25950846e+02,  2.23716094e+00]])

### Logarithm

In [113]:
np.log(a11)

array([[0.69314718, 1.09861229, 1.38629436],
       [3.13549422, 3.80666249, 4.20469262],
       [3.76120012, 4.17438727, 4.46590812]])

In [114]:
np.log(b11)

array([[3.4657359 , 3.76120012, 3.98898405],
       [2.56494936, 3.13549422, 2.7080502 ],
       [4.58496748, 3.98898405, 4.20469262]])

In [115]:
np.log(c11)

C:\Users\ramya.yande\AppData\Local\Temp\ipykernel_24084\2106220696.py:1: RuntimeWarning: invalid value encountered in log
  np.log(c11)


array([[       nan,        nan,        nan],
       [2.30258509, 3.09104245, 3.95124372],
       [       nan, 2.39789527, 2.99573227]])

### Dot product

In [116]:
a11.dot(b11)

array([[  495,   371,   421],
       [ 7887,  5642,  6406],
       [10747,  8042,  9126]])

In [117]:
b11.dot(c11)

array([[-3500,   260,  1716],
       [ -985,   151,   846],
       [-6085, -1995,  -752]])

In [118]:
c11.dot(a11)

array([[-3130, -5140, -7150],
       [ 2762,  4400,  6038],
       [ 1003,  1630,  2257]])

# Comparison

### Element wise comparison

In [119]:
a11 == b11 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [120]:
a11 < 2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### Array wise comparison

In [121]:
np.array_equal(a11, b11)

False

# Aggregate Functions

### Array-wise sum

In [122]:
p = np.array([(23,45,67), (76,65,43), (87,43,65)])
p

array([[23, 45, 67],
       [76, 65, 43],
       [87, 43, 65]])

In [123]:
q = np.array((12,34,87))
q

array([12, 34, 87])

In [124]:
r = np.array(((17,65,98), (76,65,86)))
r

array([[17, 65, 98],
       [76, 65, 86]])

In [125]:
p.sum

<function ndarray.sum>

In [126]:
q.sum

<function ndarray.sum>

### Array-wise minimum value 

In [127]:
a11.min

<function ndarray.min>

In [128]:
p.min()

23

### Maximum value of an array row

In [129]:
p.max

<function ndarray.max>

In [130]:
q.max()

87

In [131]:
r.max(axis = 0)

array([76, 65, 98])

In [132]:
p.max(axis = 0)

array([87, 65, 67])

In [133]:
p.max()

87

In [134]:
p.max(axis = 1)

array([67, 76, 87])

In [135]:
r.max()

98

### Cumulative sum of the elements

In [136]:
p.cumsum()

array([ 23,  68, 135, 211, 276, 319, 406, 449, 514])

In [137]:
p.cumsum(axis = 0)

array([[ 23,  45,  67],
       [ 99, 110, 110],
       [186, 153, 175]])

In [138]:
p

array([[23, 45, 67],
       [76, 65, 43],
       [87, 43, 65]])

In [139]:
p.cumsum(axis = 1)

array([[ 23,  68, 135],
       [ 76, 141, 184],
       [ 87, 130, 195]])

### Mean

In [140]:
p.mean()

57.111111111111114

In [141]:
p.mean

<function ndarray.mean>

In [142]:
q.mean

<function ndarray.mean>

In [143]:
q.mean()

44.333333333333336

In [144]:
np.mean(p)

57.111111111111114

### Median

In [145]:
np.median(q)

34.0

In [146]:
np.median(r)

70.5

### Standard Deviation

In [147]:
p.std()

18.799789859608328

In [148]:
np.std(p)

18.799789859608328

In [149]:
np.std(q)

31.47838764754143

### Correlation Coefficient

In [150]:
np.corrcoef(p)

array([[ 1.        , -0.98198051, -0.5       ],
       [-0.98198051,  1.        ,  0.32732684],
       [-0.5       ,  0.32732684,  1.        ]])

In [151]:
# p.corrcoef()

In [152]:
np.corrcoef(r)

array([[1.       , 0.3798191],
       [0.3798191, 1.       ]])

# Copying Arrays

### Create a view of the array with the same data

In [153]:
p.view()

array([[23, 45, 67],
       [76, 65, 43],
       [87, 43, 65]])

In [154]:
q.copy()

array([12, 34, 87])

In [155]:
np.copy(q)

array([12, 34, 87])

In [156]:
r.copy()

array([[17, 65, 98],
       [76, 65, 86]])

### Sorting Arrays

In [157]:
p.sort()

In [158]:
np.sort(p)

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [159]:
np.sort(q)

array([12, 34, 87])

In [160]:
np.sort(r)

array([[17, 65, 98],
       [65, 76, 86]])

In [161]:
p.sort(axis = 0)

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [162]:
q

array([12, 34, 87])

In [163]:
q[2]

87

In [164]:
q[1]

34

In [165]:
q[0]

12

In [166]:
p[0]

array([23, 45, 67])

In [167]:
r

array([[17, 65, 98],
       [76, 65, 86]])

In [168]:
r[1,2]

86

In [169]:
r[0, 1]

65

In [170]:
r[0,0]

17

In [171]:
r[1,1]

65

In [172]:
p

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [173]:
p[2, 2]

87

In [174]:
p[0, 1]

45

In [175]:
p[1,1]

65

In [176]:
p[1,2]

76

### Slicing

### Select items at index 0 and 1

In [177]:
q

array([12, 34, 87])

In [178]:
q[0:2]

array([12, 34])

In [179]:
q[:]

array([12, 34, 87])

In [180]:
q[0:3]

array([12, 34, 87])

In [181]:
r

array([[17, 65, 98],
       [76, 65, 86]])

In [182]:
r[0:2]

array([[17, 65, 98],
       [76, 65, 86]])

In [183]:
r[0:2, 1]

array([65, 65])

In [184]:
r[0:2, 2]

array([98, 86])

In [185]:
r[:-1]

array([[17, 65, 98]])

In [186]:
r[:-2]

array([], shape=(0, 3), dtype=int32)

In [187]:
p

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [188]:
p[0:3]

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [189]:
p[: :-1]

array([[43, 65, 87],
       [43, 65, 76],
       [23, 45, 67]])

### Boolean Indexing

In [190]:
q

array([12, 34, 87])

In [191]:
q[q<2]

array([], dtype=int32)

In [192]:
r[r<2]

array([], dtype=int32)

In [193]:
p[p<2]

array([], dtype=int32)

### Fancy Indexing

In [194]:
# b[[1, 0, 1, 0],[0, 1, 2, 0]] 
#  array([ 4. , 2. , 6. , 1.5])
# b[[1, 0, 1, 0]][:,[0,1,2,0]] 
#  array([[ 4. ,5. , 6. , 4. ], 
#  [ 1.5, 2. , 3. , 1.5],
#  [ 4. , 5. , 6. , 4. ],
#  [ 1.5, 2. , 3. , 1.5]])

# Array Manipulation

## Transposing Array

In [195]:
l = np.transpose(q)
l

array([12, 34, 87])

In [196]:
p

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [197]:
m = np.transpose(p)
m

array([[23, 43, 43],
       [45, 65, 65],
       [67, 76, 87]])

In [198]:
p.T

array([[23, 43, 43],
       [45, 65, 65],
       [67, 76, 87]])

### Changing Array Shape

In [199]:
n = p.ravel()
n

array([23, 45, 67, 43, 65, 76, 43, 65, 87])

### Reshape, but don’t change data

In [200]:
n.reshape(3, -2)

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [201]:
n.reshape(3,3)

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [202]:
# n.reshape(3,1)

### Adding or Removing Elements

### Return a new array with shape (2,6)

In [203]:
v = np.resize(2,6)
v

array([2, 2, 2, 2, 2, 2])

In [204]:
np.resize(4,20)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

### Append items to an array

In [205]:
p

array([[23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [206]:
r

array([[17, 65, 98],
       [76, 65, 86]])

In [207]:
q

array([12, 34, 87])

In [208]:
np.append(q,r)

array([12, 34, 87, 17, 65, 98, 76, 65, 86])

In [209]:
np.append(r, p)

array([17, 65, 98, 76, 65, 86, 23, 45, 67, 43, 65, 76, 43, 65, 87])

In [210]:
np.insert(q, 1,5)

array([12,  5, 34, 87])

### Delete items from an array

In [211]:
np.delete(p,[1])

array([23, 67, 43, 65, 76, 43, 65, 87])

In [212]:
np.delete(q, [1])

array([12, 87])

In [213]:
np.delete(p, [2,1])

array([23, 43, 65, 76, 43, 65, 87])

## Combining Arrays

### Concatenate arrays

In [214]:
np.concatenate((r,p))

array([[17, 65, 98],
       [76, 65, 86],
       [23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [215]:
np.concatenate((r,p), axis = 0)

array([[17, 65, 98],
       [76, 65, 86],
       [23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

### Stack arrays vertically (row-wise)

In [216]:
np.vstack((r,p))

array([[17, 65, 98],
       [76, 65, 86],
       [23, 45, 67],
       [43, 65, 76],
       [43, 65, 87]])

In [217]:
np.vstack((q,r))

array([[12, 34, 87],
       [17, 65, 98],
       [76, 65, 86]])

### Stack arrays vertically (row-wise)

In [218]:
q

array([12, 34, 87])

In [219]:
s = np.array((21,45,68))
s

array([21, 45, 68])

In [220]:
np.r_[q, s]

array([12, 34, 87, 21, 45, 68])

In [221]:
np.hstack([q, s])

array([12, 34, 87, 21, 45, 68])

### Create stacked column-wise arrays

In [222]:
np.column_stack((q,s))

array([[12, 21],
       [34, 45],
       [87, 68]])

### Create stacked column-wise arrays

In [223]:
np.c_[q,s]

array([[12, 21],
       [34, 45],
       [87, 68]])

## Splitting arrays

### Split the array horizontally at the 3rd index

In [224]:
np.hsplit(r,s)

[array([[17, 65, 98],
        [76, 65, 86]]),
 array([], shape=(2, 0), dtype=int32),
 array([], shape=(2, 0), dtype=int32),
 array([], shape=(2, 0), dtype=int32)]

In [225]:
np.vsplit(r,s)

[array([[17, 65, 98],
        [76, 65, 86]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [226]:
np.vsplit(r,2)

[array([[17, 65, 98]]), array([[76, 65, 86]])]

In [227]:
# np.hsplit(r, 2)